Audio Update
inworld-ai/inworld-unity-full pull request #205
Opened 2024-05-10 00:01 UTC by Juniverse

1. Fixed a bug for not able to speak in multi characters.
2. Used SNR to replace amplitude for better noise detecting.

2024-05-10 00:01 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/inworld-ai/inworld-unity-full?pullRequest=205) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/inworld-ai/inworld-unity-full?pullRequest=205) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: Juniverse<br/>:x: mattkwilson<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/inworld-ai/inworld-unity-full?pullRequest=205) it.</sub>

2024-05-10 23:46 UTC, mattkwilson requested changes

2024-05-10 23:46 UTC, mattkwilson commented on Assets/Inworld/Inworld.Assets/Prefabs/3D/ChatScreen.prefab
> +  m_EmotionMap: {fileID: 0}
Missing reference?

2024-05-10 23:46 UTC, mattkwilson commented on Assets/Inworld/Inworld.Native/AEC/InworldAECAudioCapture.cs
> +                        break;
I think this be simplified to just:
```
for (int i = 0; i <= inputData.Length - k_NumSamples; i += k_NumSamples)
{
```
The added lines seems to defeat the purpose of multiplying by `m_Recording.channels` in the for loops condition.

2024-05-10 23:46 UTC, mattkwilson commented on Assets/Inworld/Inworld.Samples.RPM/Scripts/InworldFacialAnimationRPM.cs
> +                    MorphState currState = m_CurrentFacial?.morphStates.FirstOrDefault(morph => morph.morphName == currIterName) ;
Remove Space

2024-05-10 23:46 UTC, mattkwilson commented on Assets/Inworld/Inworld.Samples.RPM/Scripts/UI/EmotionCanvas.cs
> +            if (InworldController.Client.Status == InworldConnectionStatus.Connected)
Are we only allowing users to mock Server Events when they are disconnected?

2024-05-13 18:25 UTC, Juniverse commented on Assets/Inworld/Inworld.Samples.RPM/Scripts/UI/EmotionCanvas.cs
> +            if (InworldController.Client.Status == InworldConnectionStatus.Connected)
Yes, applying mock events during runtime would occur some weird issues.

2024-05-13 22:32 UTC, mattkwilson commented on Assets/Inworld/Inworld.Assets/Scripts/Sample/AudioCaptureTest.cs
> +            Debug.Log("HIT");
Should this be here?

2024-05-14 21:25 UTC, mattkwilson approved these changes

2024-05-14 21:28 UTC, merged