INTG-1662 Use newtonsoft json
inworld-ai/inworld-unity-full pull request #210
Opened 2024-05-23 21:16 UTC by Juniverse

Work with https://github.com/inworld-ai/inworld-unity-core/pull/50

Related Issues: INTG-1687 INTG-1662 INTG-1588 INTG-103

2024-05-29 03:02 UTC, mattkwilson requested changes

2024-05-29 03:02 UTC, mattkwilson commented on Assets/Inworld/Inworld.Assets/Scripts/CharacterHandler/SightAngle.cs
With these changes `IsValid` will always return false and `CheckPriority` will never be called if `m_HeadTransform` or `m_CameraTransform` are not set.

2024-05-31 17:38 UTC, Juniverse commented on Assets/Inworld/Inworld.Assets/Scripts/CharacterHandler/SightAngle.cs
Updated. You still need to manually set those data if you did not drag your own PlayerController there, or our playercontroller doesn' exist.

Also CameraTransform now falls back to main camera, which isn't correct, I reverted.

2024-06-03 22:30 UTC, mattkwilson approved these changes

2024-06-03 22:42 UTC, merged