Update AEC and VAD features.
inworld-ai/inworld-unity-full pull request #227
Opened 2024-08-29 19:21 UTC by Juniverse

If VAD is enabled. When player speaking detected, we'll pause the audio playing. So that the AEC quality would be improved.

Also added back the cache list for cancelled items.

INTG-1997, INTG-1980, INTG-1967, INTG-1908

2024-08-30 22:55 UTC, mattkwilson commented on Assets/Inworld/Inworld.Editor/Editor/InworldEditor.cs
> +                if (Instance && value == Instance.m_InputUserName)
I think you may have meant this to be: `!Instance || value == Instance.m_InputUserName`, but we could also just use `!Instance`

2024-08-30 23:19 UTC, mattkwilson requested changes
AEC and VAD features appear to be working well. Please see comments and check the editor changes for the user name.

2024-08-30 23:19 UTC, mattkwilson commented on Assets/Inworld/Inworld.Samples.RPM/Prefabs/Character/Alice the Guide.prefab
Did you mean to add a Box Collider and Rigidbody?

2024-09-05 20:55 UTC, Juniverse commented on Assets/Inworld/Inworld.Editor/Editor/InworldEditor.cs
> +                if (Instance && value == Instance.m_InputUserName)
No I added this check only for preventing redundant setting.

2024-09-09 21:32 UTC, closed without merging